neovim/go-client

msgpack/decode.go
msgpack/pack.go
nvim/apidef.go
nvim/apiimp.go
nvim/apitool.go
nvim/nvim.go
nvim/nvim_test.go

Add Batch type for collecting API function calls and executing the
calls atomically using nvim_call_atomic.
Add BatchError type to represent an error from a API function call in a
Batch.
Add msgpack/Encoder.PackRaw to support the Batch type.
Bonus: Fix typo in doc comment, use T.Run() to breakup large API test.

Add support for nvim_call_atomic

---

nvim/nvim.go

Neovim has been deprecated `vim_` suffix API, change to `nvim_` suffix API.

nvim: change get_api_info to new 'nvim_' suffix API

---

nvim/apidef.go
nvim/apiimp.go

Neovim has been added new `nvim_buf_get_changedtick` API.
The function's order and godoc comment conformed to Neovim's `api/buffer.c` file.

nvim: add new BufferChangedTick(nvim_buf_get_changedtick) function

---

nvim/nvim.go
nvim/nvim_windows.go

It pops up the console (cmd.exe) for nvim.exe on Windows. This RP to hide the window.

hide the nvim exec window for Windows

---

nvim/plugin/main.go
nvim/plugin/manifest_test.go

Add feature #1. (but there is only a part of this issue)
use `--location=vimfilepath` (and simultaneously `--manifest=hostName`), only manifests with the same host name in `.vim file` are overwritten.
If an existing manifest is not defined, add it to the end of the `.vim file`.

Automatic addition of manifest

---

msgpack/common.go
msgpack/decode.go
msgpack/decode_test.go
msgpack/encode.go
msgpack/encode_test.go
msgpack/unpack.go

The value fo the "empty" field tag specifies a default value to use for
the fiend when decoding and the empty value for "omitempty" option when
encoding.

msgpack: add support for empty field tag

---

nvim/doc.go
nvim/example_test.go
nvim/helpers_test.go
nvim/nvim.go
nvim/nvim_test.go
nvim/plugin/register_test.go

Add high-level functions for creating an Nvim client. These functions
run Serve() in a goroutine by default and cleanup the goroutine in
Close().
Deprecate NewEmbedded. The NewChildProcess function is easier to use and
more flexible.

Add NewChildProces and Dial functions

---

msgpack/unpack.go

I was playing around with reading lines from a buffer and ran into a parsing error. Specifically I was getting this error ` msgpack: cannot convert Int to []uint8` and only part of one of the lines was being read.
I am also going to include the test file I used so you can run any tests you'd like.

Fixing issue with BufferLines Unpack when there are a lot of long lines

---

nvim/nvim_test.go

Add `--headless` flag to `newChildProcess` for non-exit test case.
As mentioned https://github.com/neovim/go-client/pull/36#issuecomment-469390735, The `nvim` packages `TestAPI` and `TestDial` testcases are doesn't finish (stopped) at least my local env and TravisCI.
I don't know whether this change is correct, but all testcases are not stopped and passes.
---
@justinmk
This pull request seems to be related to the core implementation of nvim, so added you as a reviewer.
Is this correct change?

nvim: add '--headless' flag to newChildProcess for non-exit testcase

---

nvim/apiimp.go
nvim/nvim.go

In order to avoid situation when NeoVim API is updated but there is no support in Golang client I propose the method `Nvim.Invoke()`. This allow everybody to use the newest API level as soon as possible. As example pull request #36 is under review about half a year.

Allow to perform naked RPC requests

---

msgpack/common.go
msgpack/common_test.go
msgpack/decode.go
msgpack/decode_test.go
msgpack/doc.go
msgpack/encode.go
msgpack/encode_test.go
msgpack/pack.go
msgpack/pack_test.go
msgpack/rpc/endpoint.go
msgpack/rpc/endpoint_test.go
msgpack/unpack.go
msgpack/unpack_test.go
nvim/apidef.go
nvim/apitool.go
nvim/doc.go
nvim/ext_test.go
nvim/helpers.go
nvim/helpers_test.go
nvim/nvim.go
nvim/nvim_test.go
nvim/plugin/eval_test.go
nvim/plugin/example_test.go
nvim/plugin/main.go
nvim/plugin/plugin.go
nvim/plugin/register_test.go
nvim/types.go

Remove license header comment.
ref: neovim/go-client#43

msgpack,nvim: remove license header comment

---

nvim/nvim_test.go

nvim: add AttachBuffer testcases

---

nvim/apidef.go
nvim/apiimp.go
nvim/apitool.go
nvim/nvim_test.go
nvim/types.go

Fix `SetBufferVirtualText` chunks arg type and fix godoc comment.
In the `chunks` arg on `SetBufferVirtualText`, `[]interface{}` type not developer friendly. Add `VirtualTextChunk` struct type and change `chunks` type to `[]VirtualTextChunk`.
The example usage exists in `nvim_test.go`.

Fix `SetBufferVirtualText` chunks arg type

---

.travis.yml
go.mod

Support Go Module.
[As I said before](https://github.com/neovim/go-client/pull/49#issuecomment-491496468), needs adding `go.mod`. Just added and fix travis test config.

Support Go module

---

nvim/apidef.go
nvim/apiimp.go
nvim/apitool.go

Implements neovim/neovim@fbf2c41 APIs.
diff:
```
> nvim_buf_del_keymap(buffer Buffer, mode String, lhs String) void { name(nvim_buf_del_keymap) }
> nvim_buf_set_keymap(buffer Buffer, mode String, lhs String, rhs String, opts Dictionary) void { name(nvim_buf_set_keymap) }
> nvim_del_keymap(mode String, lhs String) void { name(nvim_del_keymap) }
> nvim_set_keymap(mode String, lhs String, rhs String, opts Dictionary) void { name(nvim_set_keymap) }
```
Close: #53

Implements neovim/neovim@fbf2c41 APIs

---

nvim/apidef.go
nvim/apiimp.go

Change `Del` prefix to `Delete` on `nvim_del_keymap` and `nvim_buf_del_keymap`.
I made a mistake. Respect other API names.

Change `Del` prefix to `Delete`

---

nvim/nvim_test.go

Fix testcase for has been changed nvim latest error message.
Related #59

nvim: fix testcase for has been changed nvim latest error message

---

nvim/helpers.go

nvim: add missing `Module` field to `QuickfixError`.

nvim: add Module field to QuickfixError

---

.travis.yml
go.mod

Remove `1.7.x` ~ `1.10.x` Go older version support from Travis CI. And adding `1.13.x` version.
IMO, Mostly, many Go packages support the latest version and two older versions.
Especially, `1.7.x` and `1.8.x` are too old. Now I'm trying to optimize each implementation by writing the benchmark code, but there is no `testing.TB.Helper()` functions or etc. See
- https://travis-ci.org/neovim/go-client/jobs/606392860#L251
- https://travis-ci.org/neovim/go-client/jobs/606392861#L258
In the Go language community, Currently, with the release of the Go 1.13 version, the module has become almost standard. I think no needs to supporting 1.10 or older versions.
**Note that** the `go.mod` file is valid after `1.11.x`. This change does not mean that it can't compile on 1.10 or older versions. However, …

Remove older Go version support

---

nvim/apidef.go
nvim/apiimp.go
nvim/apitool.go
nvim/nvim_test.go
nvim/types.go

Add `WindowConfig` struct for `OpenWindow` API instead of `map[string]interface`.
Also, added `floating_window` testcase.
Close: #54

Add `WindowConfig` for `OpenWindow`

---

nvim/nvim_test.go

Add `colorcolumn` testcase to the `floating_window` test.
ref: neovim/neovim@d5f14b8
Close: #64

nvim: add `colorcolumn` testcase to floating_window test

---

nvim/apidef.go
nvim/apiimp.go
nvim/nvim_test.go

Implements neovim/neovim@7ce9a5c7da0f API , actually `nvim_get_runtime_file`.
Also, added testcase.

Implements neovim/neovim@7ce9a5c7da0f API (`nvim_get_runtime_file `)

---

.codecov.yml
.github/workflows/test.yml
nvim/apidef.go
nvim/apiimp.go
nvim/nvim_test.go

Remove `get_virtual_text` api and fix `extmark` raleted args

Remove get virtual text fix extmark

---

nvim/helpers.go

msgpack consistently errors out saying it cannot convert an 'int to a
string'. If you change it to an int it works as expected.

If CommandCompletionArgs.CursorPosString is a string, and not at int,

---

nvim/apidef.go
nvim/apiimp.go
nvim/apitool.go
nvim/nvim_test.go

Implements neovim/neovim@4ae31c4 APIs.

nvim: implements neovim/neovim@4ae31c4 APIs

---

.codecov.yml
.github/workflows/test.yml

Upgrade runs-on to `ubuntu-20.04` and fix codecov flags.

github/workflows: upgrade runs-on to ubuntu-20.04 and fix codecov flags

---

nvim/apidef.go
nvim/apiimp.go
nvim/apitool.go
nvim/nvim_test.go
nvim/types.go

- add `deprecatedSince(7)` to `ClearBufferHighlight`
- add `AllOptionsInfo` and `OptionInfo` methods

nvim: add deprecatedSince(7) to `ClearBufferHighlight`, add `AllOptionsInfo` and `OptionInfo`

---

nvim/api.go
nvim/api_tool.go

Support named return on `Batch` methods.

nvim: support named return on Batch methods

---

.codecov.yml
.github/workflows/test.yml
nvim/nvim_test.go
nvim/plugin/register_test.go

Support windows test

---

nvim/api.go
nvim/api_def.go
nvim/api_tool.go
nvim/nvim_test.go
nvim/types.go

Add `SetBufferText` and `Echo` apis.
```
> nvim_buf_set_text(buffer Buffer, start_row Integer, start_col Integer, end_row Integer, end_col Integer, replacement ArrayOf(String)) void { name(nvim_buf_set_text) }
> nvim_echo(chunks Array, history Boolean, opts Dictionary) void { name(nvim_echo) }
```

nvim: add SetBufferText and Echo apis

---

nvim/api.go
nvim/api_def.go
nvim/api_tool.go

nvim: refactor api

---

.github/workflows/test.yml
go.mod

github/workflow: Add `1.16.x` and drop `1.13.x`.

github/workflow: add 1.16.x and drop 1.13.x

---

nvim/api.go
nvim/api_def.go
nvim/nvim_test.go
nvim/types.go

Rename some type names.
- VirtualTextChunk and EchoChunk to TextChunk
- rename ExtMarks to ExtMark

nvim: rename some type names

---

nvim/nvim_test.go
nvim/types.go

nvim: add Buffer event types

---

nvim/api.go
nvim/api_def.go
nvim/helpers.go
nvim/nvim.go
nvim/types.go

Update documentation and small optimize.

nvim: Update documentation and small optimize

---

nvim/api.go
nvim/api_def.go
nvim/api_tool.go
nvim/nvim.go
nvim/nvim_test.go
nvim/types.go

Implements Notify, OpenTerm and HideWindow following neovim/neovim@b274b9887aba.
Close: #110

nvim: implements Notify, OpenTerm and HideWindow following neovim/neovim@b274b98

---

nvim/nvim_test.go

nvim: add skipVersion test util for API version compatibility.

nvim: add skipVersion test util for API version compatibility

---

.codecov.yml
.github/workflows/test.yml

update codecov-action to v2 and  fix codecov flags

update codecov-action to v2 and  fix codecov flags

---

nvim/api.go
nvim/api_def.go
nvim/api_deprecated.go
nvim/api_test.go
nvim/api_tool.go
nvim/nvim.go
nvim/types.go
nvim/types_test.go

nvim: support nvim v0.6.0 APIs

---

nvim/api_tool.go

nvim: fix UserCommand to non pointer on nvimTypes.

nvim: fix UserCommand to non pointer on nvimTypes

---

.github/workflows/benchmark.yml
.github/workflows/test.yml
go.mod

Upgrade go version to go1.18 and drop 1.15 support.

github/workflow: upgrade go version to go1.18 and drop 1.15 support

---

nvim/nvim.go

I'm working on a GUI for neovim and would like to support `:cq` in the GUI. 
For this reason, I propose a function in `Nvim` structure that returns the exitcode of `cmd`.

nvim: add ExitCode function

---

nvim/nvim.go

`*ProcessState.ExitCode()` return -1 if the process hasn't exited.
This PR waits for the exit of the process to get the exit code correctly.

nvim: fix ExitCode()

---

.github/workflows/labeler.yaml
nvim/nvim.go
nvim/nvim_test.go

Identified that missing `--embed flag` was causing RPC calls to `nvim_exec_lua` to hang. See #155 
**Changes:**
1. Adjusted the implementation to set `--embed` flag by default in the `nvim.NewChildProcess` function to ensure a natural default to allow RPC calls to function correctly.
2. Provided an option to override the default behavior and disable `--embed` by setting the `nvim.ChildProcessDisableEmbed()` option.
---
Close: #104

[#104] Set --embed flag by default to avoid hanging on RPC calls

---

README.md

Fixes #162.
The release process does not require keys, secrets or logins to third-party sites.

Add Release and License sections to readme file

---

nvim/api_test.go
nvim/nvim_test.go

- Get expected runtime paths by evaluating a VimL expression.
- Use equality operator to compare strings instead of reflect.DeepEqual.
- Fix typo in event name.

Improve API tests

---

.github/workflows/test.yml

Remove the go vet step. Because the go test command runs go vet, there's no need to run go vet separately.
Remove the verbose flag from the go test step. The verbose output provides little value and gets in the way of seeing the actual problems.

Improve the test workflow

---

examples/remote/README.md
examples/remote/helloremote/go.mod
examples/remote/helloremote/go.sum
examples/remote/helloremote/main.go
examples/remote/plugin/hello.lua

The example shows how to create a "remote module" as described in https://github.com/neovim/neovim/issues/27949.

Add remote module example

---

nvim/api_test.go

Do not make assumptions about how nvim_buf_set_extmark() assigns IDs.
Validate that SetBufferExtmark returned the correct ID by relying on existing test code code that compares the returned ID with the results from BufferExmarks.

Improve test TestAPI/Extmarks/Batch

---

msgpack/decode.go
msgpack/decode_test.go
msgpack/encode.go
msgpack/encode_test.go
msgpack/msgpack_bench_test.go
msgpack/msgpack_test.go
msgpack/pack_test.go
msgpack/rpc/rpc.go
msgpack/rpc/rpc_test.go
msgpack/unpack.go
msgpack/unpack_test.go
nvim/api.go
nvim/api_def.go
nvim/api_deprecated.go
nvim/api_test.go
nvim/api_tool.go
nvim/nvim.go
nvim/plugin/eval_test.go
nvim/plugin/plugin.go
nvim/plugin/plugin_test.go
nvim/types.go

The type any is an alias for type interface{}.
Closes #176

Rewrite interface{} to any

---

nvim/api.go
nvim/api_def.go

replace `valied` with `valid` in `IsBufferValid`

nvim: fix typo in api
