neovim/go-client

- nvim/doc.go
- nvim/helpers.go
- nvim/nvim.go
- Add to the package comment.
- Note that Pipeline is deprecated.
> Improve documentation

- msgpack/decode.go
Fix for issue https://github.com/neovim/go-client/issues/15
> Fix msgpack decode extension

- nvim/apidef.go
- nvim/apiimp.go
- nvim/apitool.go
- nvim/nvim.go
- nvim/nvim_test.go
> Update to latest Neovim API

- nvim/plugin/register_test.go
See https://github.com/neovim/neovim/pull/7821
> Update test for change to nvim_command_output

- .travis.yml
- go.mod
Add go 1.14.x version and drop 1.11.x version
> go.mod,travis: add go 1.14.x version and drop 1.11.x version

- nvim/nvim_test.go
> nvim: refactoring testcases

- README.md
@zchee  like this? Please check.
> Improve Reademe for usage.

- README.md
README: change GoDoc badge to pkg.go.dev.
> README: change GoDoc badge to pkg.go.dev

- .github/workflows/test.yml
- go.mod
Add go1.15.x, remove support 1.12.x.
> github: add go1.15.x, remove support 1.12.x

- .codecov.yml
- .github/workflows/test.yml
> github: set codecov.flags

- .github/workflows/test.yml
> github/workflows: use actions/cache

- .codecov.yml
- .github/workflows/test.yml
github/workflow: fix cache key.
> github/workflow: fix cache key

- .github/workflows/codeql.yml
> github/workflow: add CodeQL workflow

- .github/workflows/benchmark.yml
- .github/workflows/test.yml
- go.mod
- nvim/api_tool.go
Upgrade the Go version to 1.17.x.
> Upgrade the Go version to 1.17.x

- .github/workflows/test.yml
- nvim/nvim_test.go
github/workflow: add nightly neovim version matrix and update windows os to windows-2022.
> github/workflow: add nightly neovim version matrix and update windows os to windows-2022

- .github/workflows/test.yml
Update nvim version to v0.6.0.
> github/workflow: update nvim version to v0.6.0

- .github/workflows/benchmark.yml
- .github/workflows/codeql.yml
- .github/workflows/test.yml
- nvim/api_test.go
nvim: fix testcase for nightly.
> nvim: fix testcase for nightly

- nvim/api.go
- nvim/api_def.go
- nvim/api_test.go
Rename to `nvim{_buf}_create_user_command`.
> nvim: rename to nvim{_buf}_create_user_command

- .github/workflows/test.yml
Upgrade macos version to macos-12.
> github/workflow: upgrade macos version to macos-12

- .github/workflows/benchmark.yml
- .github/workflows/test.yml
Upgrade neovim verssion to v0.7.0.
> github/workflow: upgrade neovim verssion to v0.7.0

- .github/workflows/benchmark.yml
- .github/workflows/codeql.yml
- .github/workflows/test.yml
- msgpack/encode.go
- msgpack/msgpack_test.go
- nvim/api_def.go
- nvim/nvim.go
- nvim/plugin/plugin.go
- nvim/types.go
Update github actions to `go1.19`, drop support `go1.16.x`.
> github/workflow: update to go1.19

- nvim/api.go
- nvim/api_def.go
- nvim/api_deprecated.go
- nvim/api_test.go
- nvim/types.go
nvim: support neovim/neovim@907fc8a APIs
> nvim: support neovim/neovim@907fc8a APIs

- msgpack/msgpack_bench_test.go
- nvim/api_tool.go
- nvim/plugin/main.go
remove deprecated ioutil usage
> remove deprecated ioutil usage

- README.md
This pull request addresses minor issues with typos and grammar in the code comments. The changes ensure better clarity and readability of the code.
Changes made:
- Corrected spelling errors.
- Improved grammar and sentence structure.
- Ensured consistent use of punctuation.
Please review the changes and merge if everything looks good.
Thank you!
> README: fix typo and grammar

- nvim/api.go
- nvim/api_def.go
- nvim/api_deprecated.go
- nvim/api_tool.go
Add links from the API method documentation to the corresponding function documentation at https://neovim.io/doc/user/api.html.
Demo: https://pkg.go.dev/github.com/garyburd/docexample/nvim#Nvim.BufferLines
> Add links from Go doc to Neovim doc
